### ISSUE TITLE
Error during training the AE

### ISSUE THREAD

**Issue by Instassa** [YingqingHe/LVDM#6]
When running `bash shellscripts/train_lvdm_videoae.sh ` I get the following error:

        Traceback (most recent call last):
          File "main.py", line 250, in <module>
            model = instantiate_from_config(config.model)
          File "/home/paperspace/metaphysic/projects/marija/LVDM/lvdm/utils/common_utils.py", line 41, in instantiate_from_config
            return get_obj_from_str(config["target"])(**config.get("params", dict()))
        TypeError: __init__() got an unexpected keyword argument 'first_stage_config'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "main.py", line 514, in <module>
            if trainer.global_rank == 0:
        NameError: name 'trainer' is not defined

Any advice?

**Comment by julkaztwittera** [comment]
Yes, you have to write in line 249 the following code:
```
        config.model['ckptdir'] = ckptdir
        config.model.params.pop("first_stage_config", OmegaConf.create())
        model = instantiate_from_config(config.model)
        config.model.params['logdir'] = logdir
```
It works for me.
